FROM maven:latest
RUN apt clear && \
    apt update && \
    apt install git
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git && \
    git clone http://193.122.59.82:3000/petrovvitalik/Ansible-1.git
RUN cd /boxfuse-sample-java-war-hello && mvn package
RUN cp /boxfuse-sample-java-war-hello/target/*.war /Ansible-1/
